### ISSUE TITLE
Need to unplug/replug after every use

### ISSUE THREAD

**Issue by smunaut** [davidcarne/iceBurn#2]
Hi,

First, thanks for this utility, really useful :)

Now, I'm having an issue with it is that after using it, I need to unplug and replug the board or I get a "timeout" error from PyUSB the second time I try.

ATM I've resolved it by doing a .reset() on the board.dev before quitting but that seems a bit brute-force.

I'm using Python 3.4 and git master of pyusb.

Cheers,

   Sylvain

**Comment by martynjriley** [comment]
Hi,

You have another thanks for this utility.

The utility also works well for me. However, I have the same problem as Sylvain and have also considered the .reset() solution. I have tried both Python 3.3 and 3.4 with the same result. I note that there does seem to be some issues with libusb so I'm not sure whether the problem is related to PyUSB or libusb.

Cheers,

Martyn

**Comment by davidcarne** [comment]
Hi Folks, 

Can you let me know what platform you're using? Ideally, host platform (linux, windows, OSX), libusb version, and pyusb version?

You can find the pyusb version by running `python` and typing `usb.__version__` .

You can find the libusb version with the following commands:

-`pkg-config libusb-1.0 --modversion`
-`pkg-config libusb --modversion`

I can't recreate this on linux / libusb1 / pyusb 1.0 .
